execute "apt-get update"
package "openjdk-7-jdk"
package "ant"
package "mercurial"
package "make"
package "zip"
package "unzip"
package "build-essential"
package "libX11-dev"
package "libxext-dev"
package "libxrender-dev"
package "libxtst-dev"
package "libxt-dev"
package "libcups2-dev"
package "libfreetype6-dev"
package "libasound2-dev"
package "ccache"
